name: CI - Develop

on:
  push:
    branches:
      - develop

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar codigo
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Ejecutar pruebas
        run: ./mvnw test

      - name: Construir aplicacion
        run: ./mvnw clean package -DskipTests
