name: CI

on:
  push:
    branches:
      - develop

  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Dar permisos a Maven Wrapper
        run: chmod +x mvnw

      - name: Ejecutar pruebas
        run: ./mvnw test

      - name: Construir aplicación
        run: ./mvnw clean package -DskipTests
